@host = https://localhost:5001

### 取得 metadata
GET {{host}}/.well-known/openid-configuration HTTP/1.1

###
# @name login
POST {{host}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=client1
&client_secret=secret
&grant_type=client_credentials
&scope=api1.read

###
@authToken = {{login.response.body.access_token}}

###
# 顯示 token 內容
GET https://localhost:5101/identity HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# 用 token 取得 api
GET https://localhost:5101/api/values HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# 用 token 取得 api
GET https://localhost:5201/api/values HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
#with basic authentication
POST {{protocol}}://{{host}}:{{port}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YourCustomAPI:secret


