# 取得有 Refresh Token 的 access_token

@host = https://localhost:5001
@apihost = https://localhost:5003

### 取得 metadata
GET {{host}}/.well-known/openid-configuration HTTP/1.1

###
# @name Login
POST {{host}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=client2
&client_secret=secret
&grant_type=password
&scope=api1.read email openid offline_access
&username=demo1
&password=demo
&role=isadmin

###
@authToken = {{Login.response.body.access_token}}
@refreshToken = {{Login.response.body.refresh_token}}

###
# @name RefreshToken
POST {{host}}/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=client2
&client_secret=secret
&grant_type=refresh_token
&refresh_token={{refreshToken}}

###
# Profile
GET {{host}}/connect/userinfo HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###
# 顯示 token 內容
GET {{apihost}}/connect/userinfo HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# 用 token 取得 api
GET {{apihost}}/api/values HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

